name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Build
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python run.py

        mkdir -p /tmp/gh_pages_backup
        cp -r docs/* /tmp/gh_pages_backup/
    
    - name: Setup Git config
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Commit pages
      run: |
        git fetch origin gh-pages
        git checkout gh-pages

        find . -mindepth 1 -maxdepth 1 ! -name '.*' -exec rm -rf {} +

        cp -r /tmp/gh_pages_backup/* ./

        git add .
        git commit -m "Deploy Pages"

        git push origin gh-pages --force